name: CI/CD Docker PHP

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB DE TEST ---
  test-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, curl

      - name: Install Dependencies
        run: composer install

      - name: Run Selenium in Docker
        # On lance le container manuellement en arrière-plan avec --network host
        run: |
          docker run -d --name selenium --network host selenium/standalone-chrome:latest
          
      - name: Run PHP Server
        run: php -S 0.0.0.0:8000 -t src/ & 

      - name: Wait for services
        run: sleep 10

      - name: Run Selenium Tests
        run: php vendor/bin/phpunit tests/SeleniumTest.php
  # --- JOB DE BUILD ET PUSH ---
  build-and-push:
    needs: test-selenium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projet-php:latest